configurations {
    mockitoAgent
}

dependencies {
    def mockitoCore = libs.mockito.core.get()
    mockitoAgent("${mockitoCore.module}:${mockitoCore.versionConstraint}") {
        transitive = false
    }
}

tasks.withType(Test).configureEach {
    jvmArgs "-javaagent:${configurations.mockitoAgent.singleFile}"
}
